/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package winscope.test2;

import "protos/test/typedef.proto";

message RootMessage {
  optional InputWindowInfoProto input_window_info = 1;
}


message InputWindowInfoProto {
  optional int32 layout_params_flags = 1;
  optional int32 input_config = 2 [(.perfetto.protos.typedef) =  "android.view.WindowInsets.Side.InsetsSide"];
  optional int32 test_android_typedef = 3 [(.perfetto.protos.typedef) =  "android.content.pm.ActivityInfo.ScreenOrientation"];
  optional int32 test_android_common_typedef = 4 [(.perfetto.protos.typedef) =  "android.view.WindowManager.TransitionFlags"];
}
